bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('modify/<item_id>/', views.modify_bag, name='modify_bag'),
    path('delete/<item_id>/', views.delete_from_bag, name='delete_from_bag'),
]

blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.BlogPostList.as_view(), name='blog'),
    path('<slug:slug>/', views.BlogPostDetail.as_view(), name='post_detail'),
]

lucent_cavern/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('favorites/', include('favorites.urls')),
    path('subscriptions/', include('subscriptions.urls')),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from profiles.models import UserProfile


# Core from https://djangocentral.com/building-a-blog-application-with-django/
class BlogPost(models.Model):

    author = models.ForeignKey(UserProfile,
                               on_delete=models.CASCADE,
                               related_name='blog_posts',
                               null=False, blank=True)
    title = models.CharField(max_length=120,
                             null=True, blank=False)
    subtitle = models.CharField(max_length=180,
                                null=True, blank=False)
    content = models.TextField()
    slug = models.SlugField(unique=True,
                            max_length=250, default=None)
    created_on = models.DateTimeField(auto_now_add=True, null=False)
    updated_on = models.DateTimeField(auto_now=True, null=False)

    def __str__(self):
        return self.title

blog/views.py
from django.views import generic
from .models import BlogPost


# Core from https://djangocentral.com/building-a-blog-application-with-django/
class BlogPostList(generic.ListView):
    queryset = BlogPost.objects.order_by('-created_on')
    template_name = 'blog/blog.html'


class BlogPostDetail(generic.DetailView):
    model = BlogPost
    template_name = 'blog/post_detail.html'

blog/templates/blog/blog.html
{% extends "base.html" %}
{% load static %}


{% block content %}

    <div class="overlay-products">
        <div class="container-fluid container-margin">
            <div class="row">
                <!--Container Header-->
                <div class="col text-center">
                    <h2 class="logo-font mt-5 display-5">Our Blog</h2>
                    <hr class="w-50 mx-auto mb-5">
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-md-12 mt-3  mb-5 center">
                        <!-- Set Up core from https://simpleisbetterthancomplex.com/series/2017/09/18/a-complete-beginners-guide-to-django-part-3.html-->
                        {% for post in blogpost_list %}
                        <!-- Card element for each Blog Post -->
                        <div class="card mb-4 rounded-0 border-dark bg-transparent">
                            <div class="card-body">
                                <h2 class="card-title">{{ post.title }}</h2>
                                <p class="card-text text-dark small text-capitalize">By: {{ post.author }} | {{ post.created_on }} </p>
                                <p class="card-text text-dark">{{post.content|slice:":200" }}&hellip;</p>
                                <a href="{% url 'post_detail' post.slug  %}" class="mt-3 mb-3 btn btn-dark rounded-0 btn btn-dark btn-md text-uppercase">Read More</a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div> 
        </div>
    </div>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <div class="overlay-products">
        <div class="container container-margin">
            <div class="row">
                <!--Container Header-->
                <div class="col text-center">
                    <h2 class="logo-font mt-5 display-5">{{ object.title }}</h2>
                    <hr class="w-25 mx-auto mb-5">
                </div>
            </div>
            <!-- Set Up core from https://simpleisbetterthancomplex.com/series/2017/09/18/a-complete-beginners-guide-to-django-part-3.html-->
            <div class="row mb-5 text-center">
                <div class="col-12">
                    <h3>{{ object.subtitle }}</h3>
                    <p class="text-capitalize">Author: {{ object.author }}<br>Published: {{ object.created_on }}</p>
                    <hr class="w-100 mt-5">
                </div>
            </div>
            <div class="row">
                <div class="col-12 mx-auto mb-5 text-justify">
                    <p>{{ object.content|linebreaksbr }}</p>
                    <hr class="w-100 mt-5">
                    <a href="{% url 'blog' %}"
                        class="mt-5 mb-5 btn btn-dark rounded-0 btn btn-dark btn-md text-uppercase">Back</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}